services:
  - type: web
    name: video-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      BOT_TOKEN:
        fromSecret: BOT_TOKEN
